### ISSUE TITLE
Change in Getting Started

### ISSUE THREAD

**Issue by kalipen** [wp-net/WordPressUWP#24]
In Getting Started you mentioned :
> Before you can build you'll need to create a ApiCredentials.cs class inside the WordPressUWPApp.Utility

I think it should be 
>  Rename ApiCredentialsSample to ApiCredentials inside the WordPressUWP.Helpers

Thanks!

**Comment by ThomasPe** [comment]
actually its "copy and rename" since you don't want to delete the original sample file in case you want to push some changes to the repo. ;-)

feel free to update the readme!

**Comment by ThomasPe** [comment]
I've changed how the configuration is stored so it should be easier now.
