### ISSUE TITLE
Implement a 429 Error in Comments for WindowsArea-App

### ISSUE THREAD

**Issue by Armin2208** [wp-net/WordPressUWP#32]
Hello,

in the old WindowsArea-App sometimes a error occurred while sending a comment. It has the error code 429 and says that the comment can't be send. The error occurred random and nobody knows why :D This was a old "meme" in the windowsarea comments, before the new UWP released.

It would be awesome if you would implement a optional 429 mode in the settings. With this option activated, the app should randomly show the error 429 and don't send the comment. Maybe one of 50 comments. When the User needs again to send it, to publish the comment.

This would be the best thing you could implement. Fan Service ;)

Thank you (:

**Comment by ThomasPe** [comment]
Since this is a framework for all kinds of WordPress sites this kind of site-specific feedback should probably better be posted in the Feedback Hub.
