### ISSUE TITLE
Move Notification string to resoruce files

### ISSUE THREAD

**Issue by ThomasPe** [wp-net/WordPressUWP#35]
There are some strings for notifications (e.g. when a comment was posted) that do not yet get retrieved from the resources files and therefore are not translated.

**Comment by larsschellhas** [comment]
This was solved in 7b3c727976b29cbdb51d8b2b63d2ffe7a6ca7856 , wasn´t it?

**Comment by ThomasPe** [comment]
You're right, thanks for reminding me! ;-)
