### ISSUE TITLE
Can I pay for some support?! App crashes url is changed and JWT is configured properly

### ISSUE THREAD

**Issue by demo7up** [wp-net/WordPressUWP#38]
Im really not sure whats going on I have followed JWT install instructions to the letter and im a beginning developer.  I can send the url to my website if you can test im willing to pay!

**Comment by ThomasPe** [comment]
Can you provide your site url here or share it with me privately (e.g. through Twitter DM)?

**Comment by demo7up** [comment]
What's your Twitter

**Comment by ThomasPe** [comment]
https://twitter.com/th_p

**Comment by demo7up** [comment]
It won't let me dm you my Twitter is @demo7up

**Comment by ThomasPe** [comment]
sorry, forgot to open up dms
